query GetViewerRepositories($first: Int!, $after: String) {
  viewer {
    repositories(
      first: $first
      after: $after
      orderBy: { field: UPDATED_AT, direction: DESC }
    ) {
      edges {
        node {
          name
          stargazerCount
          updatedAt
          url
          languages(first: 5, orderBy: { field: SIZE, direction: DESC }) {
            edges {
              node {
                name
                color
              }
            }
          }
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
