name: CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache Yarn modules
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Check TypeScript types
        run: yarn tsLint

      - name: Run Linter
        run: yarn esLint

      - name: Run Tests
        run: yarn test
